### ISSUE TITLE
Quelles API BnF interroge Bibliostratus ?

### ISSUE THREAD

**Issue by JBPressac** [Transition-bibliographique/bibliostratus#35]
Bonjour,
Quelles API ou services web de la BnF interroge Bibliostratus pour aligner les données importées ?
Merci,

**Comment by Lully** [comment]
@JBPressac Bonjour
côté BnF, une seule API est utilisée : le SRU de la BnF http://catalogue.bnf.fr/api
Il est documenté sur http://api.bnf.fr

C'est décrit un peu plus en détail dans le fichier de doc technique https://github.com/Transition-bibliographique/bibliostratus/tree/master/doc (qui ne précise pas quand même les noms des critères de recherche)

**Comment by Lully** [comment]
@JBPressac Si vous avez des questions plus précises (critères utilisés, manière de les interroger, etc.), n'hésitez pas

**Comment by Lully** [comment]
Dernière précision : d'autres discussions d'utilisation se passent sur ce forum http://www.agorabib.fr/topic/3317-bibliostratus-mettre-en-correspondance-ses-notices-avec-celles-de-la-bnf/

**Comment by JBPressac** [comment]
Super, merci. Je cherche à aligner les données de [PRELIB](http://mshb.huma-num.fr/prelib/editions_list/), une base de données des acteurs de la littérature en breton. Pas sûr que Bibliostratus me permette de le faire. Peut-être que OpenRefine et le SRU de BnF seraient plus adaptés...
